### ISSUE TITLE
PDO stmt->getColumnMeta(col) should be added to the Firebird extension

### ISSUE THREAD

**Issue by frafor** [MartinKoeditz/php_firebird#2]
We were trying to migrate from interbase.so to pdo_firebird.so but we found out that it lacks some functions.

At least it lacks PDO stmt->getColumnMeta(col_num).

Hopefully this will change soon.

**Comment by MartinKoeditz** [comment]
Sorry to say. But this is the repository for the legacy Firebird driver, not PDO. You can find PDO driver here:
https://github.com/php/php-src/tree/master/ext/pdo_firebird
